Fixing typo, removing last chapter about metaheuristics (still availa…
principis/studentencursus-AI pull request #2
Opened 2020-02-17 18:58 UTC by WoutLegiest

…ble in file) and updating section about the A* algo

2020-02-21 12:37 UTC, principis requested changes

2020-02-21 12:37 UTC, principis commented on ai_automaticreasoning.tex
> +Naast zoekproblemen en het oplossen van constraint netwerken, blijkt de Artificiële intelligentie ook een uiterst geschikt domein te zijn voor logica. Al in de jaren '60 had men het droombeeld van de
```
Deze hypothese is werd gestaafd met volgende argumenten
```
pas ook even dit aan

2020-02-21 12:37 UTC, principis commented on cursusAI.tex
> +\documentclass[titlepage,a4paper,twoside]{article}
Waar gebruikt ge dit precies?

2020-02-21 12:38 UTC, principis commented
Thanks! De volgende keer wel een beetje beter uw PR verwoorden aub. Ik vraag me wel af waarvoor je de twoside gebruikt en blijkbaar heb je ook de paginanummer rechts gezet, maar dat is goed voor mij.

2020-02-27 14:01 UTC, WoutLegiest commented
Heb de commentaren gefixt. De twoside wordt gebruikt in fancyheader om te weten welke de rechter en de linker pagina is, anders worden de nummeringen automatisch uitgelijnd aan de rechterkant van het blad

2020-02-27 15:20 UTC, merged